### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by AregevDev** [MrSquaare/Icongram#3]
Would you mind of making Perl, Less, Stylus and Toml (rust dependency manager) icons?

Thanks in advance :smile:

**Comment by MrSquaare** [comment]
No problem! If you have other language icons to propose me, do not hesitate, I will try to make them as quickly as possible

**Comment by MrSquaare** [comment]
Oh, wait, I forgot the Stylus icon, I'm doing it now

**Comment by MrSquaare** [comment]
Done
